#!/bin/bash
sudo pip3 install rpi_ws281x adafruit-circuitpython-neopixel
sudo python3 -m pip install --force-reinstall adafruit-blinka
python3 make-systemd-files.py
sudo cp -fv ./tmp/*.service ./static/*.timer /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable heart-all-off.timer
sudo systemctl start heart-all-off.timer
sudo systemctl enable heart-random-animation.timer
sudo systemctl start heart-random-animation.timer
